repos:
        - repo: https://github.com/pre-commit/pre-commit-hooks
          rev: v4.0.1
          hooks:
                - id: check-yaml
                - id: end-of-file-fixer
                  exclude: \.txt$
                - id: trailing-whitespace  # Remove trailing whitespaces
        # Fix common spelling mistakes
        - repo: https://github.com/codespell-project/codespell
          rev: v2.0.0
          hooks:
                - id: codespell
                  types_or: [python, rst, markdown]
                  files: ^(geoutils|doc|tests)/

        # Replace relative imports (e.g. 'from . import georaster' -> 'from geoutils import georaster')
        - repo: https://github.com/MarcoGorelli/absolufy-imports
          rev: v0.3.0
          hooks:
                - id: absolufy-imports

        # Format the code aggressively using black
        - repo: https://github.com/psf/black
          rev: 20.8b1
          hooks:
                  - id: black
                    args: [--line-length=120]
        # Lint the code using flake8
        - repo: https://gitlab.com/pycqa/flake8
          rev: 3.9.2
          hooks:
                - id: flake8
                  args: [--max-line-length=120]
                  additional_dependencies:
                          - flake8-comprehensions==3.1.0
                          - flake8-bugbear==21.3.2
                          - pandas-dev-flaker==0.2.0
        # Lint the code using mypy
        - repo: https://github.com/pre-commit/mirrors-mypy
          rev: v0.812
          hooks:
                - id: mypy
                  args: [--strict, --ignore-missing-imports, --allow-untyped-calls]
                  additional_dependencies: [tokenize-rt==3.2.0]



        # Sort imports using isort
        - repo: https://github.com/PyCQA/isort
          rev: 5.8.0
          hooks:
                  - id: isort

        # Automatically upgrade syntax to a minimum version
        - repo: https://github.com/asottile/pyupgrade
          rev: v2.18.3
          hooks:
                - id: pyupgrade
                  args: [--py37-plus]

        # Various formattings
        - repo: https://github.com/pre-commit/pygrep-hooks
          rev: v1.8.0
          hooks:
                # Single backticks should apparently not be used
                - id: rst-backticks
                # Check that all directives end with double colon
                - id: rst-directive-colons
                  types: [text]
                  types_or: [python, rst]
                # Inline code should not touch normal text
                - id: rst-inline-touching-normal
                  types: [text]
                  types_or: [python, rst]
                # Eval should never be used (can do arbitrary code execution)
                - id: python-no-eval
                # Enforce the use of type annotations instead of docstring type comments
                - id: python-use-type-annotations
        
        # Remove unneeded #noqa comments (in case the line conforms to standards already)
        - repo: https://github.com/asottile/yesqa
          rev: v1.2.3
          hooks:
                - id: yesqa
                  additional_dependencies:
                          - flake8==3.9.2
                          - flake8-comprehensions==3.1.0
                          - flake8-bugbear==21.3.2

                        

