# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF and ePub
formats: []

conda:
  environment: doc/rtd_environment.yml