name: geoutils
channels:
  - conda-forge
dependencies:
  - python=3
  - geopandas
  - matplotlib
  - pyproj
  - rasterio
  - rioxarray
  - scipy

  # code checks
  - flake8

  # testing
  - pytest

  # development
  - pip
