# Default global parameters for GeoUtils
# See online documentation for more

[raster]

# Shift by half a pixel for "Point" pixel interpretation during raster-point operations
shift_area_or_point = True

# Raise a warning if two rasters have different pixel interpretation
warn_area_or_point = True

[resampling]

# Default resampling used during reprojection
reprojection_method = bilinear

# Default resampling used during interpolation
interpolation_method = linear

# Default distance of nodata spreading during interpolation
interpolation_dist_nodata_spread = half_order_up
