# This workflow checks that pip installation works to import the package (tests are in python-tests.yml)

name: pip-install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: ${{ matrix.os }}, python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: python -m pip install -e . -vv | tee pip.txt

      - name: Check no package is missing in setup.cfg
        run: |
          outputs = $(cat pip.txt)
          if [[  == *"Package would be ignored"* ]]; then echo "::error title=MISSING-PACKAGES::Missing packages in setup.cfg"; exit 1; fi;

      # Check import works
      - name: Check import works with base environment
        run: python -c "import geoutils"
