# This workflow checks that pip installation works to import the package (tests are in python-tests.yml)

name: pip-install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: ${{ matrix.os }}, python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Use pip install
      # Raise error if pip warns incomplete package list in setup.cfg is ignored to avoid failure in the conda feedstock
      - name: Install project
        run: |
          outputs=$(python -m pip install -e . -vv 2>&1)
          echo $outputs
          
      - name: Check not package is ignored
        if: $outputs == *"Package would be ignored"*
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Missing packages not declared in setup.cfg!')

      # Check import works
      - name: Check import works with base environment
        run: python -c "import geoutils"
